### ISSUE TITLE
Min/Max Value Bug

### ISSUE THREAD

**Issue by redkeysh** [OfficialDonut/Bitcoin#2]
Personally I see this as a bug, but the value of my bitcoin on my server is becoming of increasingly negative value, allowing it to go under a value of $0. So when a player buys bitcoin, they receive the bitcoins they purchased with no money being lost/gained.

Is it possible to make it so this isn't possible or for there to be an option to prevent this from happening?

Thanks,
Interface.

**Comment by redkeysh** [comment]
https://gyazo.com/1fb3a4677902558365649ee323e34575

**Comment by OfficialDonut** [comment]
Fixed in latest update
